// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-houses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_houses_default = defineTool({
  name: "list_houses",
  title: "Lister mes biens",
  description: "List all houses the signed-in user has access to across CasaCircle.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("houses").select("id, name, location, description, capacity, family_id").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { houses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bookings_default = defineTool2({
  name: "list_bookings",
  title: "Lister les r\xE9servations",
  description: "List bookings visible to the signed-in user. Optionally filter by house_id, status, or date range.",
  inputSchema: {
    house_id: z.string().uuid().optional().describe("Filter to a specific house."),
    status: z.enum(["pending", "approved", "refused", "cancelled"]).optional().describe("Filter by booking status."),
    from: z.string().optional().describe("ISO date; only bookings ending on/after this date."),
    to: z.string().optional().describe("ISO date; only bookings starting on/before this date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ house_id, status, from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("bookings").select("id, house_id, user_id, start_date, end_date, status, created_at").order("start_date", { ascending: false }).limit(100);
    if (house_id) q = q.eq("house_id", house_id);
    if (status) q = q.eq("status", status);
    if (from) q = q.gte("end_date", from);
    if (to) q = q.lte("start_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-booking.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_booking_default = defineTool3({
  name: "create_booking",
  title: "Cr\xE9er une r\xE9servation",
  description: "Request a booking on a house for the signed-in user. Status starts as 'pending' and awaits admin approval.",
  inputSchema: {
    house_id: z2.string().uuid().describe("The house to book."),
    start_date: z2.string().describe("Start date (YYYY-MM-DD)."),
    end_date: z2.string().describe("End date (YYYY-MM-DD), exclusive check-out.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ house_id, start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("bookings").insert({ house_id, user_id: ctx.getUserId(), start_date, end_date, status: "pending" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `R\xE9servation cr\xE9\xE9e (${data.id}) \u2014 en attente de validation.` }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_expenses_default = defineTool4({
  name: "list_expenses",
  title: "Lister les d\xE9penses",
  description: "List expenses visible to the signed-in user, optionally filtered by house.",
  inputSchema: {
    house_id: z3.string().uuid().optional().describe("Filter to a specific house.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ house_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("expenses").select("id, house_id, amount, category, description, expense_date, paid_by").order("expense_date", { ascending: false }).limit(100);
    if (house_id) q = q.eq("house_id", house_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-maintenance.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_maintenance_default = defineTool5({
  name: "list_maintenance_tickets",
  title: "Lister les tickets de maintenance",
  description: "List maintenance tickets visible to the signed-in user, optionally filtered by house or status.",
  inputSchema: {
    house_id: z4.string().uuid().optional(),
    status: z4.enum(["open", "in_progress", "resolved", "closed"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ house_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser5(ctx).from("maintenance_tickets").select("id, house_id, title, description, status, priority, created_at").order("created_at", { ascending: false }).limit(100);
    if (house_id) q = q.eq("house_id", house_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rvibaxrzubrsjummeggh";
var mcp_default = defineMcp({
  name: "casacircle-mcp",
  title: "CasaCircle",
  version: "0.1.0",
  instructions: "Outils pour CasaCircle : lister les biens, r\xE9servations, d\xE9penses et tickets de maintenance de l'utilisateur, et cr\xE9er des demandes de r\xE9servation. Toutes les actions s'ex\xE9cutent au nom de l'utilisateur connect\xE9 et respectent ses droits d'acc\xE8s.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_houses_default, list_bookings_default, create_booking_default, list_expenses_default, list_maintenance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
